name: Push notebooks

on:
  push
    branches:
      - dev
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate AAD Token
        run: |
          echo "DATABRICKS_TOKEN=$(curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
            https://login.microsoftonline.com/${{ secrets.ARM_TenantID }}/oauth2/v2.0/token \
            -d 'client_id=${{ secrets.ARM_ClientID }}' \
            -d 'grant_type=client_credentials' \
            -d 'scope=2ff814a6-3304-4ab8-85cb-cd0e6f879c1d%2F.default' \
            -d 'client_secret=${{ secrets.ARM_Secret }}' |  jq -r  '.access_token')" >> $GITHUB_ENV
